# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# List of available packages:
# * https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
# List of available sources:
# * https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3-pip
      - g++-7

dist:
  - trusty

matrix:
  include:
    # Linux {

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=clang-cxx17

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=gcc-7-cxx17

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=android-ndk-r16b-api-24-arm64-v8a-clang-libcxx14

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=analyze-cxx17

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=sanitize-address-cxx17

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=sanitize-leak-cxx17

    - os: linux
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=sanitize-thread-cxx17

    # }

    # OSX {

    - os: osx
      osx_image: xcode9.2
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=osx-10-13-make-cxx14

    - os: osx
      osx_image: xcode9.2
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=osx-10-13-cxx14

    - os: osx
      osx_image: xcode9.2
      env: PROJECT_DIR=examples/ncnn TOOLCHAIN=ios-nocodesign-11-2-dep-9-3

    # }

install:
  - source bin/hunter_env.sh

script:
  - polly.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --fwd HUNTER_SUPPRESS_LIST_OF_FILES=ON NCNN_LOCAL_TOOLCHAIN=OFF ${TEST} --install --discard 10 --tail 200
