# Source: https://raw.githubusercontent.com/ingenue/hunter/pkg.opencv/appveyor.yml

image: Visual Studio 2015

environment:

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLCHAIN: "vs-14-2015"
      PROJECT_DIR: examples\OpenCV-extra

install:
  - cmd: bin\hunter_env.cmd
  
build_script:
  - cmd: python %POLLY_ROOT%\bin\polly.py --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose --fwd HUNTER_SUPPRESS_LIST_OF_FILES=ON NCNN_LOCAL_TOOLCHAIN=OFF --install --discard 10 --tail 200

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
